title: Julian Grosshauser
author: Julian Grosshauser
url: https://juliangrosshauser.com
twitter_username: jgrosshauser
github_username:  juliangrosshauser

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: assets/images
    values:
      image: true

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - bin
  - vendor
