title: Julian's Blog
url: https://juliangrosshauser.com

author:
  name: Julian Grosshauser
  email: blog@juliangrosshauser.com

theme: minima

minima:
  skin: custom
  social_links:
    twitter: jgrosshauser
    github: juliangrosshauser

show_excerpts: true

defaults:
  - scope:
      path: assets/images
    values:
      image: true

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - bin
  - vendor
  - .idea
